# Generated by Django 5.2.6 on 2025-10-20 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilmensajero'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionMensajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='usuarios.usuario')),
            ],
        ),
    ]
