name: courier_cbe_movil
description: "Aplicaci칩n m칩vil de Courier Bolivian Express S.R.L. conectada con el backend Django REST Framework."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5

  # 游댳 Geolocalizaci칩n y mapas
  google_maps_flutter: ^2.6.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1

  # 游댳 Servicio en segundo plano
  flutter_background_service: ^5.0.4

  # 游댳 Captura de im치genes
  image_picker: ^1.0.7

  flutter_map: ^7.0.0
  latlong2: ^0.9.0

  # 游댳 UI y extras
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_spinkit: ^5.2.2
  animations: ^2.0.11

  intl: ^0.19.0
  connectivity_plus: ^6.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/  # Descomenta si tienes 칤conos personalizados
